/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev` / `next build`.
// It's committed here so the project type-checks before the first run;
// do not edit it by hand.
